apiVersion: v1
kind: Service
metadata:
  name: k8sdemoweb
  namespace: acid3
spec:
  type: LoadBalancer # NodePort
  ports:
  - protocol: TCP
    port: 3000
  selector:
    app: k8sdemoweb

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: acid3-web
  namespace: acid3
  labels:
    app: k8sdemoweb
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: k8sdemoweb
    spec:
      containers:
        - image: "giffy2499/k8sdemoweb:v7"
          imagePullPolicy: Always #IfNotPresent, Never
          name: k8sdemoweb
          ports:
            - containerPort: 3000