apiVersion: v1
kind: Service
metadata:
  name: k8sdemoapi
  namespace: acid3
spec:
  type: LoadBalancer # NodePort
  ports:
  - protocol: TCP
    port: 5001
  selector:
    app: k8sdemoapi

#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: foo
#  namespace: awesomeapps
#spec:
#  containers:
#    - name: k8sdemoapi
#      image: giffy2499/k8sdemoapi:v2
#  imagePullSecrets:
#    - name: registry-secret

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: acid3-api
  namespace: acid3
  labels:
    app: k8sdemoapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: k8sdemoapi
    spec:
      containers:
        - image: "giffy2499/k8sdemoapi:v2"
          imagePullPolicy: Always #IfNotPresent, Never
          name: k8sdemoapi
          ports:
            - containerPort: 5001