apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    version: {{ .Values.labels.version }}
    environment: {{ .Values.labels.environment }}
    tier: {{ .Values.labels.tier }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
{{ if .Values.image.useImagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Chart.Name }}-acr-secret
{{ end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        volumeMounts:
        - name: settings
          mountPath: /app/appsettings.json
          subPath: appsettings.json
          readOnly: false
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources: {{ toYaml .Values.resources | indent 12 }}
      hostAliases:
      # dev, stage & preprod
      - ip: 192.168.137.101
        hostnames:
        - azseamsacdbdv02
      volumes:
      - name: settings
        secret:
          secretName: "{{ .Chart.Name }}-config-{{ .Values.labels.environment }}"

# Note: Kubernetest support "lowcase" hostname