apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    version: {{ .Values.labels.version }}
    heritage: {{ .Release.Service }}
    environment: {{ .Values.labels.environment }}
    tier: {{ .Values.labels.tier }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.externalSSLPort }}
      targetPort: {{ .Values.service.internalSSLPort }}
      protocol: TCP
      name: https
  selector:
    app: {{ template "fullname" . }}
